version: '3.8'

services:
  go:
    container_name: go
    build:
      context: ./
    depends_on:
      - pg
    volumes:
      - ./:/app
      - .env:/app/.env
    ports:
      - ${APP_PORT}:${APP_PORT}

  pg:
    image: postgres:16.0-alpine
    container_name: skin_pg
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'

networks:
  default: